# Generated by Django 4.2.11 on 2024-03-14 09:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "topic_id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "topic_title",
                    models.CharField(max_length=20, verbose_name="Topic title"),
                ),
                ("teacher_id", models.IntegerField(blank=True, null=True)),
                ("topic_description", models.TextField(default="", max_length=200)),
                ("topic_content", models.TextField(null=True)),
                ("views", models.PositiveIntegerField(default=0, verbose_name="浏览量")),
                ("create_time", models.DateTimeField(auto_now=True)),
                (
                    "topic_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="topic_imgs/",
                        verbose_name="topic_image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyCourse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        default="请输入课程内容", verbose_name="内容"
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="课程标题")),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, max_length=20, verbose_name="更新时间"
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0, verbose_name="浏览量")),
                ("subtopic_id", models.IntegerField(verbose_name="课程id")),
                ("hint", models.TextField(blank=True, null=True)),
                ("answer", models.TextField(blank=True, null=True)),
                ("code", models.TextField(blank=True, null=True, verbose_name="骨架代码")),
                (
                    "related_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courseApp.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "ordering": ["update_date"],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_id", models.IntegerField()),
                ("like_time", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courseApp.topic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_id", models.IntegerField()),
                (
                    "progress_course",
                    models.IntegerField(null=True, verbose_name="progress_course_id"),
                ),
                ("last_practice_time", models.DateTimeField(verbose_name="上次练习时间")),
                (
                    "finished_courses",
                    models.ManyToManyField(
                        to="courseApp.mycourse", verbose_name="finished_courses"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courseApp.topic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_id", models.IntegerField(blank=True, null=True)),
                ("collect_time", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courseApp.topic",
                    ),
                ),
            ],
        ),
    ]
