# Generated by Django 4.2.11 on 2024-03-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "imageUrl",
                    models.ImageField(blank=True, null=True, upload_to="posts/"),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "author_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "avatarUrl",
                    models.ImageField(blank=True, null=True, upload_to="posts_avatar/"),
                ),
            ],
            options={
                "db_table": "my_posts",
            },
        ),
    ]
